#!/bin/sh

# $Id: start_neutrino,v 1.2 2009/04/30 19:51:00 seife Exp $

. /proc/bus/dbox.sh

etc="/var/etc"
zap="/var/tuxbox/config/zapit/zapit.conf"

if [ -e /bin/madplay ]; then
	if [ ! -e $etc/.no-mp3 ]; then
		if [ -e $etc/custom.mp3 ]; then
			madplay $etc/custom.mp3
		else
			madplay /share/gun.mp3 /share/commando.mp3
		fi
	fi
fi

[ ! -e $etc/.pmt_update ] || ZAPIT="-u"
[ -e $etc/neutrino-parameters ] && . /var/etc/neutrino-parameters

dt=`date -r /bin/saa|sed 's/....\(...\).\(..\).\(........\).....\(....\)/\4-\1-\2 \3/;s/- /-/g;\
s/Jan/1/;s/Feb/2/;s/Mar/3/;s/Apr/4/;s/May/5/;s/Jun/6/;s/Jul/7/;s/Aug/8/;s/Sep/9/;s/Oct/10/;s/Nov/11/;s/Dec/12/'`
date -s "$dt"; touch $(ls); [ ! -e /var/tuxbox/config/neutrino.conf ] && find /var -exec touch {}

if `cat /proc/bus/dreambox | grep -q 'nimtype=DVB-S'`; then
	int1=`grep "startChannelTV" $zap|cut -d "=" -f2`
	int2=`grep "lastChannelTV" $zap|cut -d "=" -f2`

	if [ -e $etc/.101 ]; then
		if [ "$int1" -lt "1000" ]; then
			sed -i "/startChannelTV/cstartChannelTV=$(($int1 + 1000))" $zap
		fi
		if [ "$int2" -lt "1000" ]; then
			sed -i "/lastChannelTV/clastChannelTV=$(($int2 + 900))" $zap
		fi
	else
		if [ "$int1" -ge "1000" ]; then
			sed -i "/startChannelTV/cstartChannelTV=$(($int1 - 1000))" $zap
		fi
		if [ "$int2" -ge "1000" ]; then
			sed -i "/lastChannelTV/clastChannelTV=$(($int2 - 1000))" $zap
		fi
	fi

	if [ -e $etc/.epg-boot ]; then
		{ sleep 60; miniops getepg >/dev/null; } &
	fi

	if [ -e $etc/.sleep ]; then
		rm -f $etc/.sleep
		{ sleep 10; wget http://localhost/control/standby?on >/dev/null 2>&1; } &
	fi
fi

sectionsd $SECTIONSD
timerd
zapit $ZAPIT
nhttpd
miniops start
[ -e $etc/.crond ] && crond &
[ -e $etc/.dp-yes ] && { sleep 300; miniops def-icon; } &

until neutrino -u ; do
    echo "Neutrino exited with nonzero exit status $?, restarting..."
    pidof sectionsd >/dev/null || sectionsd $SECTIONSD
    pidof timerd    >/dev/null || timerd
    pidof zapit     >/dev/null || zapit $ZAPIT
    pidof nhttpd    >/dev/null || nhttpd
done

[ -e /tmp/tuxmaild.pid ] && kill $( cat /tmp/tuxmaild.pid )
[ -e /tmp/tuxcald.pid ] && kill $( cat /tmp/tuxcald.pid )
[ -e /var/run/automount.pid ] && kill -TERM $( cat /var/run/automount.pid )
pzapit -kill

i=9
while expr $i != 0 > /dev/null
do
if pidof timerd > /dev/null; then echo "Waiting for timerd (max. $i seconds)"
elif pidof zapit > /dev/null; then echo "Waiting for zapit (max. $i seconds)"
elif pidof tuxmaild > /dev/null; then echo "Waiting for tuxmaild (max. $i seconds)"
elif pidof tuxcald > /dev/null; then echo "Waiting for tuxcald (max. $i seconds)"
else break;
fi
i=`expr $i - 1`
sleep 1
done

if [ -e /tmp/.nohalt ] ; then
    killall -q sectionsd
    killall -q timerd
    killall -q zapit
    killall -q nhttpd
    echo "Neutrino and its daemons terminated (hopefully)"
    exit
fi

if [ -e /tmp/.reboot ] ; then
    reboot
else
    halt
fi
