#!/bin/sh

# $Id: start_neutrino,v 1.2 2009/04/30 19:51:00 seife Exp $
# C16 changelog for this boot script:
# Sun 01 Jan 2017: prep for conditional cable nitscan plugin- AL
# Mon 02 Jan 2017: only nuke cable stuff on 1st boot (else ignore)- AL
# Tue 03 Jan 2017: prep for conditional vmautoscan plugin ??- AL
# Thu 12 Jan 2017: keep some helpfiles for cable + add SML VM help- AL
# Sun 22 Jan 2017: nuke new cable Scan scripts if Sat box- AL
# Wed 22 Mar 2017: allow for added cable shellexec menu- AL

. /proc/bus/dbox.sh

etc="/var/etc"
cfg="/var/tuxbox/config"
conf="$cfg/neutrino.conf"
zap="$cfg/zapit/zapit.conf"

if [ ! -e $etc/.no-mp3 ]; then
	if [ -e $etc/custom.mp3 ]; then
		madplay $etc/custom.mp3
	else
		madplay /share/gun.mp3 /share/commando.mp3
	fi
fi

[ ! -e $etc/.pmt_update ] || ZAPIT="-u"
[ -e $etc/neutrino-parameters ] && . /var/etc/neutrino-parameters

dt=`date -r /bin/saa|sed 's/....\(...\).\(..\).\(........\).....\(....\)/\4-\1-\2 \3/;s/- /-/g;\
s/Jan/1/;s/Feb/2/;s/Mar/3/;s/Apr/4/;s/May/5/;s/Jun/6/;s/Jul/7/;s/Aug/8/;s/Sep/9/;s/Oct/10/;s/Nov/11/;s/Dec/12/'`
date -s "$dt"; touch $(ls); [ ! -e $conf ] && find /var -exec touch {}

if `cat /proc/bus/dreambox | grep -q 'nimtype=DVB-S'`; then
	int1=`grep "startChannelTV" $zap|cut -d "=" -f2`
	int2=`grep "lastChannelTV" $zap|cut -d "=" -f2`

	if [ -e $etc/.101 ]; then
		if [ "$int1" -lt "1000" ]; then
			sed -i "/startChannelTV/cstartChannelTV=$(($int1 + 1000))" $zap
		fi
		if [ "$int2" -lt "1000" ]; then
			sed -i "/lastChannelTV/clastChannelTV=$(($int2 + 900))" $zap
		fi
	else
		if [ "$int1" -ge "1000" ]; then
			sed -i "/startChannelTV/cstartChannelTV=$(($int1 - 1000))" $zap
		fi
		if [ "$int2" -ge "1000" ]; then
			sed -i "/lastChannelTV/clastChannelTV=$(($int2 - 1000))" $zap
		fi
	fi

	if [ -e $etc/.epg-boot ]; then
		{ sleep 60; miniops getepg >/dev/null; } &
	fi
	# nuke cable stuff IF first boot
	if [ ! -e $conf ]; then
		rm -f $etc/cable*
		rm -f $etc/info/cable*
		rm -f $etc/issue.net-c
		rm -f $cfg/scan.end-c
		rm -f $cfg/scan.start-c
		rm -f $cfg/shellexec-c.conf
		rm -f $cfg/zapit/*-c.xml
		rm -f /var/bin/miniops-c
		rm -f /var/bin/stats-c
		rm -f /var/tuxbox/plugins/02-nitscan*
	fi
else
	# Cable! IF first boot, nuke 28.2E kit and apply cable settings
	if [ ! -e $conf ]; then
		. /var/etc/cable_1st.boot
		rm -f $etc/*.boot
	fi
fi

sectionsd $SECTIONSD
timerd
zapit $ZAPIT
nhttpd
miniops start
[ -e $etc/.crond ] && crond &
[ -e $etc/.dp-yes ] && { sleep 300; miniops def-icon; } &

until neutrino -u ; do
    echo "Neutrino exited with nonzero exit status $?, restarting..."
    pidof sectionsd >/dev/null || sectionsd $SECTIONSD
    pidof timerd    >/dev/null || timerd
    pidof zapit     >/dev/null || zapit $ZAPIT
    pidof nhttpd    >/dev/null || nhttpd
done

[ -e /tmp/tuxmaild.pid ] && kill $( cat /tmp/tuxmaild.pid )
[ -e /tmp/tuxcald.pid ] && kill $( cat /tmp/tuxcald.pid )
[ -e /var/run/automount.pid ] && kill -TERM $( cat /var/run/automount.pid )
pzapit -kill

i=9
while expr $i != 0 > /dev/null
do
if pidof timerd > /dev/null; then echo "Waiting for timerd (max. $i seconds)"
elif pidof zapit > /dev/null; then echo "Waiting for zapit (max. $i seconds)"
elif pidof tuxmaild > /dev/null; then echo "Waiting for tuxmaild (max. $i seconds)"
elif pidof tuxcald > /dev/null; then echo "Waiting for tuxcald (max. $i seconds)"
else break;
fi
i=`expr $i - 1`
sleep 1
done

if [ -e /tmp/.nohalt ] ; then
    killall -q sectionsd
    killall -q timerd
    killall -q zapit
    killall -q nhttpd
    echo "Neutrino and its daemons terminated (hopefully)"
    exit
fi

if [ -e /tmp/.reboot ] ; then
    reboot
else
    halt
fi
